config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Comment
      can :manage, Post, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def increase_counter
    post.comments_counter = 0 if post.comments_counter.nil?
    post.comments_counter += 1
    post.save
  end

  def decrease_counter
    return if post.comments_counter <= 0 || post.comments_counter.nil?

    post.comments_counter -= 1
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_counter
    post.likes_counter = 0 if post.likes_counter.nil?
    post.likes_counter += 1
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250, too_long: 'Maximum of 250 characters' }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def recent_comments
    comments.order(created_at: :desc).first(5)
  end

  def increase_counter
    user.posts_counter = 0 if user.posts_counter.nil?
    user.posts_counter += 1
    user.save
  end

  def decrease_counter
    return if user.posts_counter <= 0 || user.posts_counter.nil?

    user.posts_counter -= 1
    user.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :name, :email, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  def recent_posts
    posts.includes(:comments).order(created_at: :desc).last(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    user_path(current_user)
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :posts_counter, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :posts_counter, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    respond_to do |format|
      format.html do
        if @comment.save
          @comment.increase_counter
          flash[:notice] = 'Comment was successfully created.'
          redirect_to user_posts_path
        else
          flash[:alert] = 'Failed to create the comment.'
        end
      end
    end
  end

  def destroy
    @comment.decrease_counter if @comment.destroy
    redirect_to user_posts_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(user: current_user)
    if @like.save
      @like.update_counter
      flash[:notice] = 'You successfully liked the post.'
    else
      flash[:alert] = 'You were unable to give this post a like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments.all.order(created_at: :desc)
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      @post.increase_counter
      flash[:notice] = 'Post was successfully created.'
      redirect_to [@post.user, @post]
    else
      flash[:alert] = 'Failed to create the post.'
    end
  end

  def destroy
    @post.decrease_counter if @post.destroy
    redirect_to user_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(_resource)
    user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="flex">
  <p><%= comment.user.name %>:&nbsp</p>
  <p><%= comment.text %></p>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_for :comment, url: user_post_comments_path do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<div>
  <%= link_to "Back to post", user_posts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <%= render "shared/nav" %>
  </header>
  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [:user, @post] do |form| %>
  <% if post.errors.any? %>
    <div class="red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited to create this post:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <% if @comments_counter.nil? && @likes_counter.nil? %>
    <%= form.hidden_field :comments_counter, value: 0 %>
    <%= form.hidden_field :likes_counter, value: 0 %>
  <% end %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post">
  <h2><%= post.title %></h2>
  <p><%= post.text %></p>
  <span>Comments: <%= post.comments_counter || 0 %></span>
  <span>Likes: <%= post.likes_counter || 0 %></span>
</div>

app/views/posts/index.html.erb
<h1>List of recent posts from a user</h1>
<%= render partial: "users/user", object: @user %>
<% @posts.each do |post| %>
  <%= render partial: "post", object: post %>
  <%= render partial: "comments/comment", collection: post.recent_comments %>
  <%= link_to "Post details", [post.user, post] %> |
  <span>Edit this post</span>
  <% if can? :destroy, post %>
    | <%= button_to "Delete this post", user_post_path(id: post.id), method: :delete if can? :destroy, post %>
  <% end %>
<% end %>
</br>
<button>Pagination</button>
<div>
  <%= link_to "New Post", new_user_post_path if (can? :create, Post) && (@user.id == current_user.id) %>
</div>
<div>
  <%= link_to "Back to user info", user_path(@user.id) %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render "form", post: @post %>
<% if flash[:alert] %>
  <div class="red"><%= flash[:alert] %></div>
<% end %>
<br>
<div>
  <%= link_to "Back to posts", user_posts_path %>
</div>

app/views/posts/show.html.erb
<h1>Post details</h1>
<div>
  <h4><%= @post.title %> by <%= @post.user.name %></h4>
  <p><%= @post.text %></p>
  <span>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></span>
</div>
<% @comments.each do |comment| %>
  <%= render comment %>
  <% if can? :destroy, comment %>
    <%= button_to "Delete comment", user_post_comment_path(comment.user_id, comment.post_id, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>
</br>
<%= link_to "Create new comment", new_user_post_comment_path(@user.id, @post.id) %>
<%= form_with url: user_post_likes_path(@user.id, @post.id) do |f| %>
  <%= f.submit "Like this post" %>
<% end %>
<% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
<% end %>
<div>
  <%= link_to "Back to posts", [@user, :posts] %>
</div>

app/views/shared/_nav.html.erb
<nav class="flex">
  <% if user_signed_in? %>
    <%= current_user.name %>
    <%= link_to 'Logout', users_sign_out_path %> 
  <% else %>
    <span>Guest</span>
  <% end %>
</nav>

app/views/users/_user.html.erb
<div id="user_profile" class="flex user">
  <img id="<%= dom_id user %>" src=<%= user.photo %> alt="avatar">
  <div class="flex info">
    <strong><%= user.name %></strong>
    <span class="flex counter">Number of posts: <%= user.posts_counter %></span>
  </div>
</div>

app/views/users/index.html.erb
<h1>List of Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <%= link_to "Show this user", user %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>User details</h1>
<%= render @user %>
<div class="bio">
  <p>Bio:</p>
  <p><%= @user.bio %></p>
</div>

<%= render partial: "posts/post", collection: @posts %>

</br>
<%= link_to "See all posts from this user", [@user, :posts] %>
<div>
  <%= link_to "Back to users", users_path %> |
  <span>Edit this user</span> |
  <span>Destroy this user</span>
</div>